version: "3.7"

networks:
  frontend:
  backend:

services:

    modernarchitectureshop-catalog:
        image: modernarchitectureshop-basketapi:dev
        build:
            context: .
            dockerfile: src/Basket/ModernArchitectureShop.BasketApi/Dockerfile
        ports:
        - "443:55030"

    modernarchitectureshop-store:
        image: modernarchitectureshop-storeapi:dev
        build:
            context: .
            dockerfile: src/Store/ModernArchitectureShop.StoreApi/Dockerfile
        ports:
        - "443:55020"

    modernarchitectureshop-blazorui:
        image: modernarchitectureshop-blazorui:dev
        build:
            context: .
            dockerfile: src/UI/Dockerfile
        ports:
        - "443:55010"

    modernarchitectureshop-identityserver:
       image: modernarchitectureshop-identityserver:dev
       build:
            context: .
            dockerfile: src/Identity/Dockerfile
       ports:
       - "443:50000"
